### ISSUE TITLE
Battle Pets

### ISSUE THREAD

**Issue by FireWolf88** [jrowles/Gnobesy#6]
I went looking for a fix for the battle pet problem, as that's my main use for my gbank, ended up finding a [comment ](https://www.curseforge.com/wow/addons/sushi-sort?comment=91)under the addon Sushi Sort that I tweaked to make it work for Gnobesy. I have no idea how crediting would work here, but the fix is:

Turning

>  if item.id == 82800 then -- GetItemInfo returns a bogus name for caged pets
>         local speciesID, level, breedQuality, maxHealth, power, speed, name = func(id, index);
>         item.name = strjoin("#",name,level,breedQuality,maxHealth,power,speed);
>     end

Into

> if item.id == 82800 and C_TooltipInfo and C_TooltipInfo.GetGuildBankItem then -- GetItemInfo returns a bogus name for caged pets
>             local item2 = C_TooltipInfo.GetGuildBankItem(tab, i)
>             if item2 and item2.args then
>                 for _, k in ipairs(item2.args) do
>                     if k and k.field and k.field == "battlePetName" and k.stringVal then
>                         item.name = k.stringVal
>                     end
>                     if k and k.field and k.field == "battlePetSpeciesID" and k.intVal then
>                         iLevel = k.intVal
>                     end
>                 end
>             end
>         end
>     end

At least I think that's all I did, I've been screwing around with this file waay too long. I'm not a coder.

**Comment by jrowles** [comment]
Fixed with [024f210a18b2968ca60753fbd5fe4fb5211e4810](https://github.com/jrowles/Gnobesy/commit/024f210a18b2968ca60753fbd5fe4fb5211e4810).
